# Generated by Django 3.1.1 on 2020-09-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksowner',
            old_name='is_suoeruser',
            new_name='is_superuser',
        ),
    ]
